version: "3.3"

services:
  db:
    image: "postgres:12.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    tty: true
    stdin_open: true
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - .:/onebittwitter
      - app-gems:/app-gems
    depends_on:
      - db
      - redis
 

volumes:
  postgres:
  app-gems:
  redis: